tasks:
  - init: >-
      sudo apt remove tmux &&
      brew install tmux fish exa fzf &&
      curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim.appimage > ~/nvim.appimage &&
      chmod u+x ~/nvim.appimage

